export const ACTIONS = {
    ADDPAGE:'[PAGE] addPage',
    SUBTRACTPAGE:'[PAGE] subtractPage',
    CHANGEPAGE:'[PAGE] changePage',
    
    ADDPAGECHARACTER:'[CHARACTER PAGE] addPage' ,
    SUBTRACTPAGECHARACTER:'[CHARACTER PAGE] subtractPage',
    CHANGEPAGECHARACTER:'[CHARACTER PAGE] changePage',

    ADDPAGELOCATION:'[LOCATION PAGE] addPage' ,
    SUBTRACTPAGELOCATION:'[LOCATION PAGE] subtractPage',
    CHANGEPAGELOCATION:'[LOCATION PAGE] changePage',

}